name: Cleanup old releases

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Delete old releases
        uses: Nats-ji/delete-old-releases@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep-count: 5
          keep-old-minor-releases: true
          keep-old-minor-releases-count: 3
          keep-old-minor-releases-by: 'minor'
          dry-run: true
