name: Lyrical Create Debs

on:
  push:
    tags:
      - v*

jobs:
  lyrical:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          # - ubuntu: noble
          #   os: ubuntu-latest
          #   arch: amd64

          # - ubuntu: noble
          #   os: ubuntu-24.04-arm
          #   arch: arm64

          - ubuntu: resolute
            os: ubuntu-latest
            arch: amd64

          - ubuntu: resolute
            os: ubuntu-26.04-arm
            arch: arm64
    container:
      image: ubuntu:${{ matrix.ubuntu }}
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: lyrical
      - run: pip install "websockets>=13.0" --break-system-packages
      - uses: ros-tooling/action-ros-ci@v0.4
        with:
          target-ros2-distro: lyrical
          skip-tests: true
      - uses: actions/checkout@v4
        with:
          path: fkie-multi-agent-suite
      - name: Create debian packages
        run: |
          source /opt/ros/lyrical/setup.bash
          bash create_debs.sh
        shell: bash
        working-directory: fkie-multi-agent-suite
      - name: Upload debs to release ${{ github.ref }}
        uses: svenstaro/upload-release-action@v2
        with:
          file: fkie-multi-agent-suite/ros-lyrical-fkie-mas-*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
